# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-08 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='message',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
